### ISSUE TITLE
listrecipient() ->Contact->CreatedAt vide ?

### ISSUE THREAD

**Issue by fturk** [mailjet/mailjet-apiv3-php-simple#69] opened 2015-03-16 10:55 UTC
Requête:

$params = array(
    "style" => "full",
    "Limit" => -1
);
$mj->listrecipient($params);

Resultat :
Contact": {
    "CreatedAt": "",
    "DeliveredCount": 0,
    "Email":
    {
        "Email": "toto@test.fr"
    },
    "ID": 55,
    "IsOptInPending": false,
    "IsSpamComplaining": false,
    "LastActivityAt": "",
    "LastUpdateAt": "",
    "Name": "",
    "UnsubscribedAt": "",
    "UnsubscribedBy": ""
},
"ID": 420,
"IsActive": true,
"IsUnsubscribed": false,
"List":
{
    "Address": "",
    "CreatedAt": "",
    "ID": 75,
    "IsDeleted": false,
    "Name": "Test 1",
    "SubscriberCount": 0
},
"UnsubscribedAt": ""

**Comment by arnaudbreton** [comment] 2015-03-17 08:26
Hi @fturk,

Thanks for reporting, it looks our system is not sending back all the informations when using full style. I opened an issue on our side and we'll come back to you ASAP when fixed.

Thanks for your patience.
Arnaud.

**Comment by arnaudbreton** [comment] 2015-06-02 17:08
Hi @fturk,

The issue is now fixed on our side and you should be able to get the information when listing your `listrecipient` ressources.

Could you please confirm it's fixed on your side?

Thanks for your patience on this,
Arnaud.

**Closed** 2015-06-09 17:06 UTC
